import { Metadata } from "next";
import { ReactNode } from "react"; // Import ReactNode for typing children
import "./globals.css";
import LayoutWrapper from "../components/LayoutWrapper"; // Import the client-side layout wrapper

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the type for children prop
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        {/* The LayoutWrapper handles Header, Navbar, and FontProvider */}
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
