import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";
import Navbar from "../components/Navbar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {/* Full-width header */}
                <Header />

                {/* Main container for sidebar and content */}
                <div className="flex">
                    {/* Sidebar Navigation */}
                    <Navbar />

                    {/* Main Content Area */}
                    <div className="flex-grow">{children}</div>
                </div>
            </body>
        </html>
    );
}
