import { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "../components/LayoutWrapper"; // Import the client-side layout wrapper

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* The LayoutWrapper handles Header, Navbar, and FontProvider */}
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
